### ISSUE TITLE
code of segmentation 

### ISSUE THREAD

**Issue by creater-zq** [cuiziteng/Illumination-Adaptive-Transformer#1]
Hello! Will the split training code be published？
thanks!

**Comment by cuiziteng** [comment]
Hi! Thanks you, this paper is still under-review, I'd release the code as soon as possible~

**Comment by cuiziteng** [comment]
Segmentation code uploaded, and our paper also renew the segmentation results in https://arxiv.org/abs/2205.14871 , please check~

**Comment by creater-zq** [comment]
thanks


| |
张取
|
|
***@***.***
|
---- Replied Message ----
| From | Cui ***@***.***> |
| Date | 10/11/2022 21:24 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [cuiziteng/Illumination-Adaptive-Transformer] code of segmentation (Issue #1) |

Segmentation code uploaded, and our paper also renew the segmentation results in https://arxiv.org/abs/2205.14871 , please check~
