### ISSUE TITLE
IAT_enhance training issues

### ISSUE THREAD

**Issue by Xinjie-Wei** [cuiziteng/Illumination-Adaptive-Transformer#10]
Thank you for your job in this paper, here my issues is that different results got when I trained the IAT_enhance code every time, how to 
 make the model is stable?

**Comment by cuiziteng** [comment]
Hi, thanks for your interesting! 

Do you mean LOL-V1 or LOL-V2 dataset training? BTW, could you provide the training log here?

**Comment by Xinjie-Wei** [comment]
Sorry , may I not state clearly ,I just use LOL-V1 dataset to training and I just cite the global branch code  for my  model, but I find the model is't stable if adding your global branch code. Sometimes will got good result but sometimes may got terrible result.
Would you know what reason will make this situation?

**Comment by cuiziteng** [comment]
It's OK, if use it to your our model you may need to change some parameter or network structure, you could add my wechat to discuss: a1094691089.
