### ISSUE TITLE
how to create high-low pairs for custom dataset?

### ISSUE THREAD

**Issue by Vincent630** [cuiziteng/Illumination-Adaptive-Transformer#12]
how to create high-low pairs for custom dataset?

**Comment by cuiziteng** [comment]
Hello, If you only have high light image, I think you could translate it to it's pair low-light data by using some function, such as gamma correction (x**gamma), and the gamma value should set larger than 1, such as 2.0~3.5, for more detail you could see the paper MBLLEN' Sec 4.1: http://bmvc2018.org/contents/papers/0700.pdf.

**Comment by jolt2017** [comment]
There are also some detailed methods like this CVPR 2022 paper: https://openaccess.thecvf.com/content/CVPR2022/papers/Punnappurath_Day-to-Night_Image_Synthesis_for_Training_Nighttime_Neural_ISPs_CVPR_2022_paper.pdf.

##############################
this git  did not offer the source code.

**Comment by cuiziteng** [comment]
Hahh, I got no idea about that, so you can use the simple way to generate low-light data.
