### ISSUE TITLE
About segmentation

### ISSUE THREAD

**Issue by noringname** [cuiziteng/Illumination-Adaptive-Transformer#14]
Hi,

Thank you for your excellent work! I have a question regarding segmentation (probably a dumb question):
Can I directly use IAT for segmentation? I mean, use the local M&A, global color&gamma to get the segmentation image, since segmentation image is basically a similar image in another "color domain".

Thanks.

**Comment by ryeocthiv** [comment]
Hello,

Thanks for your interesting question. The IAT mainly focuses on low level task (i.e. image enhancement), and we will try to use it directly for segmentation tasks later.
