### ISSUE TITLE
Data_highlight error in exposure.py

### ISSUE THREAD

**Issue by FiyinfobaO** [cuiziteng/Illumination-Adaptive-Transformer#15]
**For context**: I am working on an instance segmentation problem with some images that are blurry so I'm hoping that IAT can sharpen and make my images better. 
I started with the `evaluation_exposure` code to use the trained model on my images, but I get an error from test_loader in [line 49](https://github.com/cuiziteng/Illumination-Adaptive-Transformer/blob/main/IAT_enhance/evaluation_exposure.py#L49) which is a result of the `test_dataset` created from the `exposure_header`. I decide to play with the exposure_header first from exposure.py.

**Problem**: 
I'm trying to test the exposure.py on my custom dataset. I keep getting a resize error on [line 98](https://github.com/cuiziteng/Illumination-Adaptive-Transformer/blob/main/IAT_enhance/data_loaders/exposure.py#L98) which is as a result of the `data_highlight` being empty/none as you can see in the ss below

<img width="1512" alt="Screen Shot 2022-10-20 at 11 04 36 AM" src="https://user-images.githubusercontent.com/67701124/197000625-086b6506-2beb-4ef3-8f05-1438b9070ccb.png">

But if you look at the path in the warning shown in the ss, that path can be traced to [line 90](https://github.com/cuiziteng/Illumination-Adaptive-Transformer/blob/main/IAT_enhance/data_loaders/exposure.py#L90) which can further be traced to the `self.high_path` in [line 41](https://github.com/cuiziteng/Illumination-Adaptive-Transformer/blob/main/IAT_enhance/data_loaders/exposure.py#L41). 

So, I'm trying to understand what is really happening in line 41 because if you replace the folder name (`INPUT_IMAGES`) with the expert folder name, there is no way when it will find an image in the folder when it gets to line 90 to read the image. Or is there something I'm missing?

**Comment by cuiziteng** [comment]
I get your problem, let me write a code for demo.py.

**Comment by cuiziteng** [comment]
Hello, the Reason you could not use the original data-loader is that, that data-loader only used for the exposure correction dataset.

I've add a new file, please use [IAT_enhance/img_demo.py](https://github.com/cuiziteng/Illumination-Adaptive-Transformer/blob/main/IAT_enhance/img_demo.py) to generate your own dataset, please check.

**Comment by FiyinfobaO** [comment]
Thanks. I will look at the demo file you added
