### ISSUE TITLE
请问一下大佬在论文里面的LOL数据集指标是v1版本还是v2版本的

### ISSUE THREAD

**Issue by developWmark** [cuiziteng/Illumination-Adaptive-Transformer#18]

**Comment by cuiziteng** [comment]
你好，论文两个都有，我们把两个数据集的结果都给出来了，在正文的Table.1中。

**Comment by developWmark** [comment]
![image](https://user-images.githubusercontent.com/93702453/202074404-a34c2599-7834-488a-a526-23e3b64f8de1.png)很抱歉再次打扰你，table1只看到了用IAT(local)和IAT以及其他对比模型的实验结果，未看到LOL1和LOL2的区别。还有一个问题是我按照你的代码和提供的数据在LOLV2上做了多次实验，包括3090和v100，IAT(local)最好一次是19.32psnr，IAT最好一次是22.5 psnr，未达到你论文的实验效果，请问一下当时你的torch版本和cuda版本是多少呀

**Comment by developWmark** [comment]
很抱歉再次打扰你，table1只看到了用IAT(local)和IAT以及其他对比模型的实验结果，未看到LOL1和LOL2的区别。还有一个问题是我按照你的代码和提供的数据在LOLV2上做了多次实验，包括3090和v100，IAT(local)最好一次是19.32psnr，IAT最好一次是22.5 psnr，未达到你论文的实验效果
![image](https://user-images.githubusercontent.com/93702453/202077765-b3f9be6c-e626-472f-a449-6e02b0bf6d7d.png)
