### ISSUE TITLE
Test code

### ISSUE THREAD

**Issue by perohzy** [cuiziteng/Illumination-Adaptive-Transformer#2]
Hello, have you released the test code

**Comment by cuiziteng** [comment]
Hi, the [evaluation_exposure.py](https://github.com/cuiziteng/Illumination-Adaptive-Transformer/blob/main/IAT_enhance/evaluation_exposure.py) and [evaluation_lol.py](https://github.com/cuiziteng/Illumination-Adaptive-Transformer/blob/main/IAT_enhance/evaluation_lol.py) are the test code, if you want see the generate image, direct set the --save to true.

**Comment by cuiziteng** [comment]
Any question else please let me know~

**Comment by perohzy** [comment]
Hello, as a beginner, I'm honored to see your article. It's very helpful to me. Thank you.

**Comment by cuiziteng** [comment]
You're welcome!
