### ISSUE TITLE
About MIT-Adobe FiveK dataset

### ISSUE THREAD

**Issue by DeniJsonC** [cuiziteng/Illumination-Adaptive-Transformer#20]
Dear authors,
First, thanks your work,
I wander could you release the FiveK pretrained model or image results or your training detail, e.g. method of constructing your training set and testing set(full-resolution test, center-crop test or resize test?). I did not find the detail in your paper.
Thanks again.

**Comment by cuiziteng** [comment]
Thanks for your interest in our paper~ 

We're following 3D-LUT paper's setting and train the IAT model (full-resolution setting).
