### ISSUE TITLE
没看懂joint training是怎么实现的

### ISSUE THREAD

**Issue by mhn2836** [cuiziteng/Illumination-Adaptive-Transformer#22]
求教

**Comment by cuiziteng** [comment]
前面的IAT网络（暗光增强数据预训练）+后面的high level检测分割网络（正常数据集预训练）前后接起来一起学习，然后在暗光/多光照场景的数据集上面跑就行了。

**Comment by mhn2836** [comment]
> 前面的IAT网络（暗光增强数据预训练）+后面的high level检测分割网络（正常数据集预训练）前后接起来一起学习，然后在暗光/多光照场景的数据集上面跑就行了。

那么相对于分步实现暗光增强和High level任务，损失函数需要改动吧，具体的改动体现在哪呢？

**Comment by cuiziteng** [comment]
这部分设计的很简单，可以看代码，一个最终的检测/分割损失函数就好了，不需要额外增加图像增强的损失函数，因为没有增强图像的ground truth。

**Comment by cuiziteng** [comment]
https://github.com/cuiziteng/Illumination-Adaptive-Transformer/blob/main/IAT_high/IAT_mmdetection/mmdet/models/detectors/IAT_detector/IAT_yolo.py

和

https://github.com/cuiziteng/Illumination-Adaptive-Transformer/blob/main/IAT_high/IAT_mmdetection/mmdet/models/dense_heads/yolo_head.py

**Comment by mhn2836** [comment]
> https://github.com/cuiziteng/Illumination-Adaptive-Transformer/blob/main/IAT_high/IAT_mmdetection/mmdet/models/detectors/IAT_detector/IAT_yolo.py
> 
> 和
> 
> https://github.com/cuiziteng/Illumination-Adaptive-Transformer/blob/main/IAT_high/IAT_mmdetection/mmdet/models/dense_heads/yolo_head.py

我比对了下代码，所以是在原生Yolo backbone前面加入pre_encoder，也就是图像增强网络，并加入对应的预训练权重，但是head并没有进行改进，我理解的对吗？

**Comment by cuiziteng** [comment]
对～

**Comment by mhn2836** [comment]
> 

明白了，非常感谢大佬耐心的解答

**Comment by e96031413** [comment]
@cuiziteng 您好，我在[IAT_high/IAT_mmdetection/configs/yolo/yolov3_IAT_lol.py](https://github.com/cuiziteng/Illumination-Adaptive-Transformer/blob/main/IAT_high/IAT_mmdetection/configs/yolo/yolov3_IAT_lol.py#L6-L7)看到LOL_pretrain.pth

```python
pre_encoder = dict(type='IAT', in_dim=3, with_global=True,
                           init_cfg=dict(type='Pretrained', checkpoint='LOL_pretrain.pth'))
```

想請問pre_encoder的weight (LOL_pretrain.pth)，是在[IAT_enhance](https://github.com/cuiziteng/Illumination-Adaptive-Transformer/tree/main/IAT_enhance)資料夾底下，進行訓練所得到的pre-trained weight嗎？
