### ISSUE TITLE
The results on LOL_v2 (23.50) can not be reproduced

### ISSUE THREAD

**Issue by caiyuanhao1998** [cuiziteng/Illumination-Adaptive-Transformer#23]
I follow the instruction and run your training code on LOL v2, but I can not reproduce the result 23.50 as you claim in your paper.

The following is my training log. The highest result I achieve is 22.27, **which is 1.23 dB lower than the result your claim**.

epoch0:the SSIM is8.087733478546143the PSNR is0.002048975680809235
epoch1:the SSIM is8.088865766525268the PSNR is0.0020592276645766106
epoch2:the SSIM is8.089015655517578the PSNR is0.0020607898640446366
epoch3:the SSIM is8.092512950897216the PSNR is0.002110693720605923
epoch4:the SSIM is8.107489285469056the PSNR is0.0023968358349520714
epoch5:the SSIM is8.126581797599792the PSNR is0.0029918855470896233
epoch6:the SSIM is8.130081911087036the PSNR is0.003118420476675965
epoch7:the SSIM is8.1347114610672the PSNR is0.003303283171990188
epoch8:the SSIM is9.364255285263061the PSNR is0.1271097839483991
epoch9:the SSIM is9.16264506340027the PSNR is0.15450223885476588
epoch10:the SSIM is9.44221969127655the PSNR is0.16575233253301122
epoch11:the SSIM is9.397988185882568the PSNR is0.16541616997215897
epoch12:the SSIM is9.173627004623413the PSNR is0.16644690200686454
epoch13:the SSIM is9.324027357101441the PSNR is0.17883807219564915
epoch14:the SSIM is9.332916088104248the PSNR is0.18411239743232727
epoch15:the SSIM is9.342347326278686the PSNR is0.18545244827866555
epoch16:the SSIM is9.502512502670289the PSNR is0.18909531101584434
epoch17:the SSIM is9.189135470390319the PSNR is0.18498291939496994
epoch18:the SSIM is9.45021318435669the PSNR is0.19496413365006446
epoch19:the SSIM is9.409765496253968the PSNR is0.1961538675427437
epoch20:the SSIM is9.483068218231201the PSNR is0.19775634534657002
epoch21:the SSIM is9.308093452453614the PSNR is0.19468286514282226
epoch22:the SSIM is8.880097970962524the PSNR is0.18796637557446957
epoch23:the SSIM is9.51645984172821the PSNR is0.1881718859146349
epoch24:the SSIM is9.49911026954651the PSNR is0.20294105345848948
epoch25:the SSIM is9.545482378005982the PSNR is0.20213593212189152
epoch26:the SSIM is9.177079362869263the PSNR is0.1965278576919809
epoch27:the SSIM is9.285028009414672the PSNR is0.20318413108587266
epoch28:the SSIM is9.465926122665405the PSNR is0.20649954790249467
epoch29:the SSIM is9.49543381690979the PSNR is0.20732622556388378
epoch30:the SSIM is9.463562355041503the PSNR is0.20903204560279845
epoch31:the SSIM is9.291701903343201the PSNR is0.20764187574386597
epoch32:the SSIM is9.414807925224304the PSNR is0.21313096955418587
epoch33:the SSIM is9.505392618179322the PSNR is0.21754048734903336
epoch34:the SSIM is9.548325209617614the PSNR is0.21932661771774292
epoch35:the SSIM is9.689799785614014the PSNR is0.2172734509408474
epoch36:the SSIM is11.326832609176636the PSNR is0.42970519214868547
epoch37:the SSIM is12.097051992416382the PSNR is0.45192137330770493
epoch38:the SSIM is12.108901233673096the PSNR is0.4577687734365463
epoch39:the SSIM is12.134007730484008the PSNR is0.45994638234376906
epoch40:the SSIM is14.819394245147706the PSNR is0.6323583891987801
epoch41:the SSIM is13.88424765586853the PSNR is0.6375490626692772
epoch42:the SSIM is16.15067547798157the PSNR is0.6712370264530182
epoch43:the SSIM is16.84523286819458the PSNR is0.6787651240825653
epoch44:the SSIM is15.793723659515381the PSNR is0.6702643635869027
epoch45:the SSIM is21.030127229690553the PSNR is0.720447798371315
epoch46:the SSIM is18.878737859725952the PSNR is0.7041552656888962
epoch47:the SSIM is15.812010383605957the PSNR is0.6824253845214844
epoch48:the SSIM is18.272259569168092the PSNR is0.7075494581460953
epoch49:the SSIM is19.14011833190918the PSNR is0.7157443058490753
epoch50:the SSIM is19.75078754425049the PSNR is0.70861931681633
epoch51:the SSIM is18.9529935836792the PSNR is0.7231519252061844
epoch52:the SSIM is17.565703630447388the PSNR is0.7109767854213714
epoch53:the SSIM is19.927125244140626the PSNR is0.7307237017154694
epoch54:the SSIM is13.245184111595155the PSNR is0.6611121767759323
epoch55:the SSIM is14.259756126403808the PSNR is0.6798404389619828
epoch56:the SSIM is18.353997020721437the PSNR is0.725360432267189
epoch57:the SSIM is17.181971883773805the PSNR is0.7142825800180436
epoch58:the SSIM is15.248561553955078the PSNR is0.6917109596729278
epoch59:the SSIM is16.100279521942138the PSNR is0.7060170668363571
epoch60:the SSIM is15.62862624168396the PSNR is0.7005516910552978
epoch61:the SSIM is18.026970005035402the PSNR is0.728149493932724
epoch62:the SSIM is14.66194447040558the PSNR is0.6921924173831939
epoch63:the SSIM is20.986934204101562the PSNR is0.7493051582574844
epoch64:the SSIM is14.842319316864014the PSNR is0.692627962231636
epoch65:the SSIM is17.87742868423462the PSNR is0.7316201043128967
epoch66:the SSIM is17.4865380859375the PSNR is0.7278870522975922
epoch67:the SSIM is12.416836204528808the PSNR is0.6637853768467903
epoch68:the SSIM is17.835995893478394the PSNR is0.7312469232082367
epoch69:the SSIM is16.867292585372926the PSNR is0.7223180675506592
epoch70:the SSIM is15.043827333450317the PSNR is0.7049058598279953
epoch71:the SSIM is18.28393283843994the PSNR is0.7395702272653579
epoch72:the SSIM is15.750820951461792the PSNR is0.7093107008934021
epoch73:the SSIM is17.910083618164062the PSNR is0.738815747499466
epoch74:the SSIM is16.975306930541993the PSNR is0.7311065232753754
epoch75:the SSIM is16.89947772026062the PSNR is0.7301295822858811
epoch76:the SSIM is20.26647385597229the PSNR is0.740372611284256
epoch77:the SSIM is16.505825624465942the PSNR is0.7267972123622894
epoch78:the SSIM is21.83123019218445the PSNR is0.7703090327978134
epoch79:the SSIM is19.131819086074827the PSNR is0.7546422576904297
epoch80:the SSIM is19.270853757858276the PSNR is0.7551278030872345
epoch81:the SSIM is15.424377698898315the PSNR is0.7155910110473633
epoch82:the SSIM is21.81715867996216the PSNR is0.7762155348062515
epoch83:the SSIM is21.811316356658935the PSNR is0.7767966914176941
epoch84:the SSIM is17.97213460922241the PSNR is0.7481774538755417
epoch85:the SSIM is18.35736382484436the PSNR is0.750209914445877
epoch86:the SSIM is15.428206663131714the PSNR is0.5713698762655258
epoch87:the SSIM is18.758892393112184the PSNR is0.7424249410629272
epoch88:the SSIM is17.986881761550904the PSNR is0.7505625778436661
epoch89:the SSIM is18.468367404937744the PSNR is0.754635505080223
epoch90:the SSIM is20.086836576461792the PSNR is0.7446396207809448
epoch91:the SSIM is14.462214426994324the PSNR is0.7082636988162995
epoch92:the SSIM is19.336383323669434the PSNR is0.763331601023674
epoch93:the SSIM is18.322897539138793the PSNR is0.7549965381622314
epoch94:the SSIM is18.265445442199706the PSNR is0.7555335426330566
epoch95:the SSIM is21.713954944610595the PSNR is0.7810935515165329
epoch96:the SSIM is15.725410623550415the PSNR is0.5960508106648922
epoch97:the SSIM is14.563313207626344the PSNR is0.7140893012285232
epoch98:the SSIM is18.21999987602234the PSNR is0.7559380060434342
epoch99:the SSIM is17.75634081840515the PSNR is0.751667065024376
epoch100:the SSIM is20.955784845352174the PSNR is0.7759920537471772
epoch101:the SSIM is15.668734588623046the PSNR is0.7253268772363662
epoch102:the SSIM is17.165053215026855the PSNR is0.7469641673564911
epoch103:the SSIM is18.833919086456298the PSNR is0.7641947948932648
epoch104:the SSIM is16.217777976989748the PSNR is0.738413507938385
epoch105:the SSIM is21.86265477180481the PSNR is0.7826292431354522
epoch106:the SSIM is12.418989157676696the PSNR is0.6870645892620086
epoch107:the SSIM is18.74344668388367the PSNR is0.7643512219190598
epoch108:the SSIM is19.363833227157592the PSNR is0.7699980366230011
epoch109:the SSIM is16.480025587081908the PSNR is0.7395291632413864
epoch110:the SSIM is15.913087167739867the PSNR is0.7283277601003647
epoch111:the SSIM is17.884775133132933the PSNR is0.7570178210735321
epoch112:the SSIM is17.565268602371216the PSNR is0.7538213121891022
epoch113:the SSIM is16.209891815185546the PSNR is0.7383643460273742
epoch114:the SSIM is21.440790662765504the PSNR is0.7785607451200485
epoch115:the SSIM is17.32880214691162the PSNR is0.7528532201051712
epoch116:the SSIM is19.70276083946228the PSNR is0.7748844337463379
epoch117:the SSIM is17.63582950592041the PSNR is0.7562901169061661
epoch118:the SSIM is15.7072762298584the PSNR is0.7332599568367004
epoch119:the SSIM is21.900884675979615the PSNR is0.785164424777031
epoch120:the SSIM is17.804091482162477the PSNR is0.7585563415288925
epoch121:the SSIM is17.469445686340332the PSNR is0.7559246391057968
epoch122:the SSIM is16.390553722381593the PSNR is0.7446260994672775
epoch123:the SSIM is15.457445831298829the PSNR is0.7307127636671066
epoch124:the SSIM is21.621181554794312the PSNR is0.7918656283617019
epoch125:the SSIM is17.147320766448974the PSNR is0.7530309516191482
epoch126:the SSIM is18.366084785461425the PSNR is0.7654437285661697
epoch127:the SSIM is17.666581907272338the PSNR is0.7572830951213837
epoch128:the SSIM is18.08206847190857the PSNR is0.7583408373594284
epoch129:the SSIM is20.993405542373658the PSNR is0.78799953520298
epoch130:the SSIM is18.25806077003479the PSNR is0.7667574292421341
epoch131:the SSIM is18.386504182815553the PSNR is0.7672714722156525
epoch132:the SSIM is21.447270183563234the PSNR is0.7756754046678543
epoch133:the SSIM is14.857528347969055the PSNR is0.725698059797287
epoch134:the SSIM is17.231627950668337the PSNR is0.7559036511182785
epoch135:the SSIM is17.14563900947571the PSNR is0.7554481935501098
epoch136:the SSIM is20.516077556610107the PSNR is0.7864747589826584
epoch137:the SSIM is19.254506397247315the PSNR is0.773221623301506
epoch138:the SSIM is19.53445689201355the PSNR is0.7787765276432037
epoch139:the SSIM is17.92858470916748the PSNR is0.7646408253908157
epoch140:the SSIM is17.38410093307495the PSNR is0.7585772436857223
epoch141:the SSIM is17.273456325531004the PSNR is0.7584405261278152
epoch142:the SSIM is22.27366545677185the PSNR is0.7973577392101288
epoch143:the SSIM is19.163390388488768the PSNR is0.7674860900640488
epoch144:the SSIM is18.307440128326416the PSNR is0.7696155053377152
epoch145:the SSIM is21.99427290916443the PSNR is0.7879052954912186
epoch146:the SSIM is22.253810300827027the PSNR is0.800685196518898
epoch147:the SSIM is18.29346939086914the PSNR is0.7660909217596054
epoch148:the SSIM is17.774317817687987the PSNR is0.7641811102628708
epoch149:the SSIM is18.83606019973755the PSNR is0.774753816127777
epoch150:the SSIM is13.575250096321106the PSNR is0.5420715890824794
epoch151:the SSIM is12.165990781784057the PSNR is0.6845450216531753
epoch152:the SSIM is16.016698656082152the PSNR is0.7457981079816818
epoch153:the SSIM is17.3633150100708the PSNR is0.7614045649766922
epoch154:the SSIM is16.599908723831177the PSNR is0.7480748361349105
epoch155:the SSIM is21.92375214576721the PSNR is0.7989856678247452
epoch156:the SSIM is15.753748655319214the PSNR is0.7423879826068878
epoch157:the SSIM is16.669842796325682the PSNR is0.7529749315977097
epoch158:the SSIM is19.109032850265503the PSNR is0.7790273940563202
epoch159:the SSIM is17.659239616394043the PSNR is0.6955675482749939
epoch160:the SSIM is15.61527027130127the PSNR is0.7409330749511719
epoch161:the SSIM is20.80841049194336the PSNR is0.7934250444173813
epoch162:the SSIM is19.143077726364137the PSNR is0.7776496255397797
epoch163:the SSIM is18.061606245040892the PSNR is0.7687737762928009
epoch164:the SSIM is19.48025318145752the PSNR is0.7149681413173675
epoch165:the SSIM is16.415246982574462the PSNR is0.7511044263839721
epoch166:the SSIM is18.244335222244263the PSNR is0.7719787734746933
epoch167:the SSIM is18.655969123840332the PSNR is0.7746826803684235
epoch168:the SSIM is20.060618057250977the PSNR is0.7855126345157624
epoch169:the SSIM is12.833550271987916the PSNR is0.7036039894819259
epoch170:the SSIM is14.796231870651246the PSNR is0.7333997768163681
epoch171:the SSIM is17.536999616622925the PSNR is0.7655161887407302
epoch172:the SSIM is17.586996259689332the PSNR is0.7659162974357605
epoch173:the SSIM is21.547703704833985the PSNR is0.799209000468254
epoch174:the SSIM is22.191434860229492the PSNR is0.7976007878780365
epoch175:the SSIM is17.663445348739625the PSNR is0.767403804063797
epoch176:the SSIM is18.215603590011597the PSNR is0.7720106196403503
epoch177:the SSIM is22.20205388069153the PSNR is0.7916523277759552
epoch178:the SSIM is15.181844701766968the PSNR is0.7384664863348007
epoch179:the SSIM is16.79238655090332the PSNR is0.7569806915521622
epoch180:the SSIM is18.550804386138918the PSNR is0.7764493399858474
epoch181:the SSIM is19.14839900970459the PSNR is0.7813882011175156
epoch182:the SSIM is21.030886335372927the PSNR is0.7970479828119278
epoch183:the SSIM is21.34168800354004the PSNR is0.7789803957939148
epoch184:the SSIM is14.066535563468934the PSNR is0.5486951971054077
epoch185:the SSIM is17.94793242454529the PSNR is0.7697372353076934
epoch186:the SSIM is17.471632318496702the PSNR is0.7631015777587891
epoch187:the SSIM is21.15422629356384the PSNR is0.7489640510082245
epoch188:the SSIM is14.998249855041504the PSNR is0.7360540914535523
epoch189:the SSIM is19.16685203552246the PSNR is0.7827498018741608
epoch190:the SSIM is18.87566258430481the PSNR is0.7799750733375549
epoch191:the SSIM is21.584044857025148the PSNR is0.8008593368530273
epoch192:the SSIM is22.135481195449827the PSNR is0.803409098982811
epoch193:the SSIM is19.77601598739624the PSNR is0.787899569272995
epoch194:the SSIM is18.60330771446228the PSNR is0.7776092529296875
epoch195:the SSIM is18.680255575180055the PSNR is0.7773879325389862
epoch196:the SSIM is14.2812508392334the PSNR is0.7256510895490647
epoch197:the SSIM is18.16931573867798the PSNR is0.7692664313316345
epoch198:the SSIM is16.864282789230348the PSNR is0.7603274828195572
epoch199:the SSIM is19.35522621154785the PSNR is0.7849405640363694

**Comment by cuiziteng** [comment]
Hello, from my training experience the results are mostly larger than 23, I encourage that you may try more times~ thanks

**Comment by caiyuanhao1998** [comment]
I completely follow your instruction and run.

I do not know what the problem is.

Can you share your training log to help me debug? Thanks

**Comment by cuiziteng** [comment]
The original training logs has been deleted, I'll train a new model for you now and reply to you later~

**Comment by cuiziteng** [comment]
Yes, the results are not stable on LOL-V2 dataset, but usually more than 23, here's the log I just training:

epoch0:the SSIM is9.419963994026183the PSNR is0.22051885209977626
epoch1:the SSIM is9.483481621742248the PSNR is0.23023993641138077
epoch2:the SSIM is9.496299209594726the PSNR is0.23206186100840567
epoch3:the SSIM is9.545529532432557the PSNR is0.23894545629620553
epoch4:the SSIM is9.637264881134033the PSNR is0.24208321616053582
epoch5:the SSIM is11.62248592376709the PSNR is0.46109207570552824
epoch6:the SSIM is11.826118383407593the PSNR is0.46643156856298446
epoch7:the SSIM is11.688558521270751the PSNR is0.4686175587773323
epoch8:the SSIM is11.899561471939087the PSNR is0.4707530143857002
epoch9:the SSIM is12.223397121429443the PSNR is0.45502268105745314
epoch10:the SSIM is12.031927547454835the PSNR is0.48326083838939665
epoch11:the SSIM is11.685614156723023the PSNR is0.4736013913154602
epoch12:the SSIM is12.411297492980957the PSNR is0.5050741040706634
epoch13:the SSIM is17.854457445144654the PSNR is0.7572916781902314
epoch14:the SSIM is13.71010293006897the PSNR is0.7088137364387512
epoch15:the SSIM is18.920688858032225the PSNR is0.7695623362064361
epoch16:the SSIM is17.540207843780518the PSNR is0.75668103992939
epoch17:the SSIM is19.857937965393067the PSNR is0.7788832825422287
epoch18:the SSIM is20.591227378845215the PSNR is0.7881690675020218
epoch19:the SSIM is17.33897213935852the PSNR is0.7598787438869476
epoch20:the SSIM is18.446453313827515the PSNR is0.7705205935239792
epoch21:the SSIM is20.433978223800658the PSNR is0.7889452028274536
epoch22:the SSIM is19.912425928115844the PSNR is0.7892772805690765
epoch23:the SSIM is22.053683128356933the PSNR is0.80651691198349
epoch24:the SSIM is17.5731360912323the PSNR is0.7660753911733628
epoch25:the SSIM is19.952772579193116the PSNR is0.7881462079286575
epoch26:the SSIM is22.115043020248415the PSNR is0.7938952571153641
epoch27:the SSIM is14.498058099746704the PSNR is0.7289807695150375
epoch28:the SSIM is19.001850242614747the PSNR is0.7829511284828186
epoch29:the SSIM is17.873606986999512the PSNR is0.7715202647447587
epoch30:the SSIM is18.21032245635986the PSNR is0.7750930106639862
epoch31:the SSIM is20.930246381759645the PSNR is0.7837090289592743
epoch32:the SSIM is19.09557906150818the PSNR is0.7872218924760819
epoch33:the SSIM is18.164276704788207the PSNR is0.7767714488506318
epoch34:the SSIM is19.596869592666625the PSNR is0.7919654136896134
epoch35:the SSIM is17.713692026138304the PSNR is0.7701816141605378
epoch36:the SSIM is15.908085861206054the PSNR is0.7511686009168624
epoch37:the SSIM is23.240506963729857the PSNR is0.8129621541500092
epoch38:the SSIM is19.059943513870238the PSNR is0.7888702410459518
epoch39:the SSIM is17.453100671768187the PSNR is0.7717405015230179
epoch40:the SSIM is22.21875880241394the PSNR is0.8134740060567855
epoch41:the SSIM is17.807348136901854the PSNR is0.7764607334136963
epoch42:the SSIM is19.90813751220703the PSNR is0.7956102448701858
epoch43:the SSIM is18.459588603973387the PSNR is0.782816122174263
epoch44:the SSIM is22.499762220382692the PSNR is0.8121301490068435
epoch45:the SSIM is20.490990695953368the PSNR is0.8024340152740479
epoch46:the SSIM is19.65520362854004the PSNR is0.796124677658081
epoch47:the SSIM is18.345483827590943the PSNR is0.7847332817316055
epoch48:the SSIM is19.55862126350403the PSNR is0.7947113919258117
epoch49:the SSIM is15.261826467514037the PSNR is0.746801700592041
epoch50:the SSIM is14.218616051673889the PSNR is0.7330719918012619
epoch51:the SSIM is18.865271759033202the PSNR is0.7894499766826629
epoch52:the SSIM is18.323637199401855the PSNR is0.7844726461172103
epoch53:the SSIM is18.802765445709227the PSNR is0.7892011147737503
epoch54:the SSIM is15.103858823776244the PSNR is0.7463065159320831
epoch55:the SSIM is20.79625521659851the PSNR is0.8051516133546829
epoch56:the SSIM is17.07516495704651the PSNR is0.7691056019067765
epoch57:the SSIM is19.713531370162965the PSNR is0.7986353915929795
epoch58:the SSIM is22.1729602432251the PSNR is0.8118325299024582
epoch59:the SSIM is20.633663291931153the PSNR is0.8029637455940246
epoch60:the SSIM is22.38649221420288the PSNR is0.8170311570167541
epoch61:the SSIM is19.027523803710938the PSNR is0.7931163614988327
epoch62:the SSIM is16.792685232162476the PSNR is0.7689049232006073
epoch63:the SSIM is18.911387424468995the PSNR is0.7904827284812928
epoch64:the SSIM is14.460332975387573the PSNR is0.7358492547273636
epoch65:the SSIM is22.243622093200685the PSNR is0.8152115768194199
epoch66:the SSIM is19.328510398864747the PSNR is0.7958617621660232
epoch67:the SSIM is18.250196084976196the PSNR is0.7863944226503372
epoch68:the SSIM is16.933549528121947the PSNR is0.7398923015594483
epoch69:the SSIM is20.270446977615357the PSNR is0.8036634790897369
epoch70:the SSIM is18.714022359848023the PSNR is0.7900630235671997
epoch71:the SSIM is16.42916281700134the PSNR is0.7651382344961166
epoch72:the SSIM is22.084891357421874the PSNR is0.8175656116008758
epoch73:the SSIM is20.847763328552247the PSNR is0.8054946821928024
epoch74:the SSIM is20.04250288963318the PSNR is0.8043160128593445
epoch75:the SSIM is17.911831274032593the PSNR is0.7820742082595825
epoch76:the SSIM is15.60463939666748the PSNR is0.7544172888994217
epoch77:the SSIM is16.33248052597046the PSNR is0.7654699528217316
epoch78:the SSIM is19.462728290557862the PSNR is0.7950931143760681
epoch79:the SSIM is18.364586143493653the PSNR is0.7880344825983048
epoch80:the SSIM is18.791941690444947the PSNR is0.7922592693567276
epoch81:the SSIM is17.788961782455445the PSNR is0.7805846977233887
epoch82:the SSIM is21.245304737091065the PSNR is0.8133137500286103
epoch83:the SSIM is18.438447551727293the PSNR is0.7883914238214493
epoch84:the SSIM is18.472170915603638the PSNR is0.7886141449213028
epoch85:the SSIM is18.42163411140442the PSNR is0.7879230123758316
epoch86:the SSIM is15.617772092819214the PSNR is0.754835501909256
epoch87:the SSIM is17.854942541122437the PSNR is0.7851785171031952
epoch88:the SSIM is17.777697486877443the PSNR is0.783046070933342
epoch89:the SSIM is18.75137758255005the PSNR is0.7931232136487961
epoch90:the SSIM is17.22336386680603the PSNR is0.7762840574979782
epoch91:the SSIM is21.115719699859618the PSNR is0.8134823805093765
epoch92:the SSIM is19.006640090942383the PSNR is0.795650041103363
epoch93:the SSIM is17.264933757781982the PSNR is0.7764900988340377
epoch94:the SSIM is19.215055618286133the PSNR is0.7952567893266678
epoch95:the SSIM is19.198702249526978the PSNR is0.7940487676858902
epoch96:the SSIM is21.785034618377686the PSNR is0.8182976204156875
epoch97:the SSIM is20.338378410339356the PSNR is0.8061614966392517
epoch98:the SSIM is18.66173258781433the PSNR is0.7916275107860565
epoch99:the SSIM is14.679605569839477the PSNR is0.744861308336258
epoch100:the SSIM is17.3424454498291the PSNR is0.7598205441236496
epoch101:the SSIM is19.160427265167236the PSNR is0.7921322566270829
epoch102:the SSIM is20.271581230163573the PSNR is0.8071405130624771
epoch103:the SSIM is18.95785584449768the PSNR is0.7963250309228898
epoch104:the SSIM is21.964187936782835the PSNR is0.8107736223936081
epoch105:the SSIM is16.38295820236206the PSNR is0.7649771970510483
epoch106:the SSIM is22.33350372314453the PSNR is0.8214414930343628
epoch107:the SSIM is18.542120761871338the PSNR is0.7921316981315613
epoch108:the SSIM is18.092781896591188the PSNR is0.7877384889125824
epoch109:the SSIM is19.381777210235597the PSNR is0.7961966931819916
epoch110:the SSIM is18.911775341033934the PSNR is0.7950486266613006
epoch111:the SSIM is17.975303592681886the PSNR is0.7838061952590942
epoch112:the SSIM is18.531460123062132the PSNR is0.7925693094730377
epoch113:the SSIM is18.341051635742186the PSNR is0.7904746419191361
epoch114:the SSIM is20.435574026107787the PSNR is0.7860759282112122
epoch115:the SSIM is14.891453037261963the PSNR is0.745704996585846
epoch116:the SSIM is19.594048767089845the PSNR is0.8024809241294861
epoch117:the SSIM is16.452242879867555the PSNR is0.7686488807201386
epoch118:the SSIM is22.627765865325927the PSNR is0.8220214885473252
epoch119:the SSIM is21.157637748718262the PSNR is0.7876599690318108
epoch120:the SSIM is17.373203687667846the PSNR is0.777764738202095
epoch121:the SSIM is18.5335044670105the PSNR is0.793004829287529
epoch122:the SSIM is13.58526258468628the PSNR is0.7285144358873368
epoch123:the SSIM is23.14468957901001the PSNR is0.8222071608901024
epoch124:the SSIM is22.411488742828368the PSNR is0.8196491259336471
epoch125:the SSIM is18.84061441421509the PSNR is0.7972998088598251

**Comment by caiyuanhao1998** [comment]
Thanks! What kind of GPU did you use? I used RTX 8000 to train on LOLv2

I guess I have to try more times.

**Comment by cuiziteng** [comment]
I use Tesla V100, thanks~
