### ISSUE TITLE
detection

### ISSUE THREAD

**Issue by PeterSmith1** [cuiziteng/Illumination-Adaptive-Transformer#26]
大佬，这IAT如何集成到YOLOV5上呢，我看原文采用的是YOLOV3去做检测任务的

**Comment by cuiziteng** [comment]
这个简单，mmdetection的话直接在[这里](https://github.com/cuiziteng/Illumination-Adaptive-Transformer/tree/main/IAT_high/IAT_mmdetection/mmdet/models/detectors/IAT_detector)改，加上你的新模型比如YOLOV5，然后configs里面加一下就好了，可以仿照我怎么添加的YOLOV3和DETR来写一下。

**Comment by PeterSmith1** [comment]
> 这个简单，mmdetection的话直接在[这里](https://github.com/cuiziteng/Illumination-Adaptive-Transformer/tree/main/IAT_high/IAT_mmdetection/mmdet/models/detectors/IAT_detector)改，加上你的新模型比如YOLOV5，然后[configs](https://github.com/cuiziteng/Illumination-Adaptive-Transformer/tree/main/IAT_high/IAT_mmdetection/configs/yolo)里面加一下就好了，可以仿照我怎么添加的YOLOV3和DETR来写一下。

谢谢大佬

**Comment by NMU-wmb** [comment]
@PeterSmith1 你好，使用yolov5改好了吗？
