### ISSUE TITLE
run demo

### ISSUE THREAD

**Issue by Licy641** [cuiziteng/Illumination-Adaptive-Transformer#27]
Hi, could you please tell me why when I run the img_demo.py,the output is like this:
![QKE`{XLRGCPLAT2ND7UF1~C](https://user-images.githubusercontent.com/52774319/222326546-8cb8189b-b581-49da-a38f-1641196fb336.png)
and when I run exposure part,it posts CUDA out of memory.

**Comment by cuiziteng** [comment]
Sincerely sorry for that.

This is caused by the original image load method is matplotlib.pyplot, I've corrected the demo.py, please check that ~

**Comment by Licy641** [comment]
got it,thanks for your reply.
