### ISSUE TITLE
CUDA outof memory

### ISSUE THREAD

**Issue by Mr-ind1fferent** [cuiziteng/Illumination-Adaptive-Transformer#28]
3060怎么推理跑不动会直接炸，用这个模型跑视频的

**Comment by cuiziteng** [comment]
多少显存的3060啊，输入尺寸多少？

你可以试试这个：torch.utils.checkpoint ，把这个加在模型(model.py)里，显存能减少好多。

**Comment by Mr-ind1fferent** [comment]
6gb

**Comment by Mr-ind1fferent** [comment]
> 6gb

是在推理过程中，非训练，显存不足

**Comment by cuiziteng** [comment]
哦哦，你把图像缩小，或者用这个[torch.utils.checkpoint](https://blog.csdn.net/ONE_SIX_MIX/article/details/93937091)试试看呢。

**Comment by Mr-ind1fferent** [comment]
在哪里更改图片大小

**Comment by cuiziteng** [comment]
你加载的时候resize一下就好啦
