### ISSUE TITLE
运行evaluation_lol报错

### ISSUE THREAD

**Issue by zkzk123zk** [cuiziteng/Illumination-Adaptive-Transformer#3]
运行evaluation_lol报错
ssim_value = ssim(enhanced_img, high_img, as_loss=False).item()
ValueError: only one element tensors can be converted to Python scalars

**Comment by cuiziteng** [comment]
Thanks for your question! 
In fact I can use it, may be the problem is the version of "IQA-pytorch", my "IQA-pytorch" version is 0.1, please check~

**Comment by zkzk123zk** [comment]
> Thanks for your question! In fact I can use it, may be the problem is the version of "IQA-pytorch", my "IQA-pytorch" version is 0.1, please check~



> Thanks for your question! In fact I can use it, may be the problem is the version of "IQA-pytorch", my "IQA-pytorch" version is 0.1, please check~

Thanks,But my IQA-pytorch version is 0.1

**Comment by cuiziteng** [comment]
你有改这个代码什么地方吗，可以print一下enhanced_img和high_img这两个变量还是不是tensor。

**Comment by zkzk123zk** [comment]
> 你有改这个代码什么地方吗，可以print一下enhanced_img和high_img这两个变量还是不是tensor。

Thank you very much!My gpu_id is 0 on my computer,but the gpu_id is set to 1 in the "train_lol.py",the gpu_id is set to 0 in the "evalution_lol.py",I have set the gpu_id is 0 in the "train_lol.py",the program running successfully!
