### ISSUE TITLE
關於LOL_pretrain.pth

### ISSUE THREAD

**Issue by e96031413** [cuiziteng/Illumination-Adaptive-Transformer#31]
@cuiziteng 您好，之前在[没看懂joint training是怎么实现的 #22](https://github.com/cuiziteng/Illumination-Adaptive-Transformer/issues/22)有看到您對joint training的說明

我在[IAT_high/IAT_mmdetection/configs/yolo/yolov3_IAT_lol.py](https://github.com/cuiziteng/Illumination-Adaptive-Transformer/blob/main/IAT_high/IAT_mmdetection/configs/yolo/yolov3_IAT_lol.py#L6-L7)看到LOL_pretrain.pth

```
pre_encoder = dict(type='IAT', in_dim=3, with_global=True,
                           init_cfg=dict(type='Pretrained', checkpoint='LOL_pretrain.pth'))
```
想請問pre_encoder的weight (LOL_pretrain.pth)，是在[IAT_enhance](https://github.com/cuiziteng/Illumination-Adaptive-Transformer/tree/main/IAT_enhance)資料夾底下，根據不同的dataset，進行訓練得到的pre-trained weight嗎？

**Comment by cuiziteng** [comment]
您好，感谢关注。
没错，这个就是在IAT_enhance里面pretrain的权重，是LOL-V2数据集上面训练的权重。

**Comment by e96031413** [comment]
了解了，感謝您的回覆
