### ISSUE TITLE
IAT_YOLOV3

### ISSUE THREAD

**Issue by PeterSmith1** [cuiziteng/Illumination-Adaptive-Transformer#34]
作者您好，我直接按照您写的readme去运行您的IAT_yolov3,直接显示模型IAT_YOLOV3没有注册，然后加上注册代码后又报错

**Comment by cuiziteng** [comment]
您好，请确认下mmdet版本哈，然后您可以把报错发一下

**Comment by PeterSmith1** [comment]
> 您好，请确认下mmdet版本哈，然后您可以把报错发一下

![image](https://user-images.githubusercontent.com/54202525/225193236-ee1226da-d238-4499-86a4-a2a2ce2b9eee.png)

**Comment by PeterSmith1** [comment]
mmdet版本readme是一致的

**Comment by cuiziteng** [comment]
这个应该是没问题的，因为在[代码这里](https://github.com/cuiziteng/Illumination-Adaptive-Transformer/blob/main/IAT_high/IAT_mmdetection/mmdet/models/detectors/__init__.py)已经注册过了。你的mmcv版本也一致吗？

**Comment by PeterSmith1** [comment]
> 这个应该是没问题的，因为在[代码这里](https://github.com/cuiziteng/Illumination-Adaptive-Transformer/blob/main/IAT_high/IAT_mmdetection/mmdet/models/detectors/__init__.py)已经注册过了。你的mmcv版本也一致吗？

谢谢大佬，已解决

**Comment by cuiziteng** [comment]
客气了。
