### ISSUE TITLE
您好，我把IAT搭建在yolov5上，但是为什么加上global分支效果不好？

### ISSUE THREAD

**Issue by Henryluoluoluo** [cuiziteng/Illumination-Adaptive-Transformer#36]

**Comment by cuiziteng** [comment]
您好，可能是因为没加载预训练权重？

**Comment by Henryluoluoluo** [comment]
忘加梯度裁剪了😅

**Comment by PeterSmith1** [comment]
> 忘加梯度裁剪了😅

请问一下，您是怎么加到yolov5的？

**Comment by ahnu313** [comment]
您好，我想问一下，你将IAT-YOLOv5后的结果是如何呢？在弱光检测方面是升了还是降了？

**Comment by PeterSmith1** [comment]
你需要针对你的数据集去单独构建一个类似LOL低光数据集的数据集去训练IAT权重

从 Windows 版邮件发送

发件人: ahnu313
发送时间: 2024年1月17日 11:37
收件人: cuiziteng/Illumination-Adaptive-Transformer
抄送: PeterSmith1; Comment
主题: Re: [cuiziteng/Illumination-Adaptive-Transformer] 您好，我把IAT搭建在yolov5上，但是为什么加上global分支效果不好？ (Issue #36)

您好，我想问一下，你将IAT-YOLOv5后的结果是如何呢？在弱光检测方面是升了还是降了？

**Comment by ahnu313** [comment]
> 你需要针对你的数据集去单独构建一个类似LOL低光数据集的数据集去训练IAT权重 从 Windows 版邮件发送 发件人: ahnu313 发送时间: 2024年1月17日 11:37 收件人: cuiziteng/Illumination-Adaptive-Transformer 抄送: PeterSmith1; Comment 主题: Re: [cuiziteng/Illumination-Adaptive-Transformer] 您好，我把IAT搭建在yolov5上，但是为什么加上global分支效果不好？ (Issue #36) 您好，我想问一下，你将IAT-YOLOv5后的结果是如何呢？在弱光检测方面是升了还是降了？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>



> 你需要针对你的数据集去单独构建一个类似LOL低光数据集的数据集去训练IAT权重 从 Windows 版邮件发送 发件人: ahnu313 发送时间: 2024年1月17日 11:37 收件人: cuiziteng/Illumination-Adaptive-Transformer 抄送: PeterSmith1; Comment 主题: Re: [cuiziteng/Illumination-Adaptive-Transformer] 您好，我把IAT搭建在yolov5上，但是为什么加上global分支效果不好？ (Issue #36) 您好，我想问一下，你将IAT-YOLOv5后的结果是如何呢？在弱光检测方面是升了还是降了？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

恩恩谢谢，我目前操作一直是按论文里的简单方法【先增强再训练检测】，在yolo3 5 8都尝试过，在v3上确实是存在一点精度的上升，但是在v5和v8上测试都是下降的，现在打算使用IAT替换一下yolo的backbone，或者使用pre-encoder的方法继续尝试，但是深度学习能力受限不知道应该如何操作
