### ISSUE TITLE
training

### ISSUE THREAD

**Issue by PeterSmith1** [cuiziteng/Illumination-Adaptive-Transformer#38]
大佬好，我看你训练IAT-YOLOV3是单卡训练，我拿单卡3090去训练，时间太长了，如果要八卡一起训练的话，我采用你训练detr的训练参数文件，就会出错，如果想八卡同时训练，该怎么设置呢

**Comment by cuiziteng** [comment]
您好，IAT-YOLOV3单卡的话一般四五个小时就好，八卡detr您那里报错是什么，可以看一下吗

**Comment by PeterSmith1** [comment]
![image](https://user-images.githubusercontent.com/54202525/230750881-0ab92b3d-9ca8-4417-8868-8edbccb2f73a.png)
我是直接拿detr的多卡训练文件去训练YOLO的

**Comment by cuiziteng** [comment]
看样子是有一部分的参数没有进入梯度传播，你可以先把find_unused_parameter=True这部分设置成False
