### ISSUE TITLE
损失函数

### ISSUE THREAD

**Issue by LitterWindwind** [cuiziteng/Illumination-Adaptive-Transformer#42]
您好，我注意到损失函数两个数据集不一样，只对LOLV2训练的时候使用了L1_smooth_loss和vgg-loss，能方便问下原因吗？ 感兴趣是不是两类数据集的差别原因导致这么选取？

**Comment by cuiziteng** [comment]
是的，因为发现这样设置损失函数在这两个数据集的效果分别最好，算是个trick吧
