### ISSUE TITLE
怎么得到分割指标

### ISSUE THREAD

**Issue by liangxiwen123** [cuiziteng/Illumination-Adaptive-Transformer#43]
您好，非常感谢您的开源代码。
我在运行的时候出现一些问题，在运行python tools/test.py configs/deeplabv3plus/deeplabv3plus_r50_IAT_MIT5K.py work_dir/IAT_MIT5K/iter_20000.pth --eval mIoU这个命令时，是一张1080ti显卡在运行，而且时间特别慢，需要半天。我想问问是不是哪个参数没有传对，但是结果是正确的，想问问您这个该怎么解决。

还有一个问题，我如果只想对比别的模型的分割效果，我可以直接使用增强后的图片放到MBLLEN的指定路径，然后运行python tools/test.py configs/deeplabv3plus/deeplabv3plus_r50-d8_1024x1024_80k_ACDC_night.py work_dir/baseline/iter_20000.pth --eval mIoU计算出结果就行，还是需要增强整个训练集，重新训练？

**Comment by cuiziteng** [comment]
您好，如果只想对比别的模型的分割效果，我们在论文baseline中的做法是用增强算法增强整个训练集，重新训练，然后做对比。
