### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by PINTO0309** [cuiziteng/Illumination-Adaptive-Transformer#5]
Thank you for sharing your great code. :smiley_cat:

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.
- DETR ONNX, YOLOv3 ONNX, Low-LightEnhancement ONNX, ExposureCorrection ONNX
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/315_Illumination-Adaptive-Transformer

Thank you.

**Comment by cuiziteng** [comment]
Hi, I've finished it, thanks for your advice!

**Comment by PINTO0309** [comment]
Thanks!
