### ISSUE TITLE
LOL-v2数据集训练模型

### ISSUE THREAD

**Issue by 2665207323** [cuiziteng/Illumination-Adaptive-Transformer#53]
为什么我用LOL-v2数据集按照readme中的方法训练得到的模型，用img_demo.py测试的时候，增强之后的图片是一片蓝色呢

**Comment by cuiziteng** [comment]
<img width="469" alt="image" src="https://github.com/cuiziteng/Illumination-Adaptive-Transformer/assets/55396225/ba9141ee-a716-4330-8a98-93605c8b79c1">
您好，LOL-V2这里是True您设置了吗
