### ISSUE TITLE
请问pre-train的模型在哪里下载

### ISSUE THREAD

**Issue by evehal** [cuiziteng/Illumination-Adaptive-Transformer#55]
显卡不行，想直接用训练好的模型试试，谢谢大佬

**Comment by cuiziteng** [comment]
<img width="604" alt="image" src="https://github.com/cuiziteng/Illumination-Adaptive-Transformer/assets/55396225/dc5fd7b4-44b2-4d98-b32a-975d28e1adea">
这种蓝色字点进去就可以下载～

**Comment by HilbertMaximov** [comment]
你好，请问这个截图页面在哪里呀，这个项目的主页没有网盘链接，谢谢
