### ISSUE TITLE
About LOL dataset

### ISSUE THREAD

**Issue by echosum** [cuiziteng/Illumination-Adaptive-Transformer#6]
Hi

Could you please tell me the difference between the original LOL dataset with LOL-v2?

Best

**Comment by cuiziteng** [comment]
The original LOL has 15 test image, and the renewed LOL has 100 test image, you can replace this dataset to LOL-v1, it's both OK.

**Comment by echosum** [comment]
Thanks for your reply. Could you please tell me how you achieve RGB to RAW and ISP process? I didn't see that in your script.

**Comment by cuiziteng** [comment]
Thanks for your question, in this arxiv version we have not clearly show this process, this is also mentioned by the ECCV's reviewer, so we have renewed our arxiv version, the renewed arxiv version would be released in these days, please keep an eye on this project, thanks!

**Comment by echosum** [comment]
Hi, I am still confused how you convert the original LOL dataset into renewed LOL.  I want to ensure the results shown in your paper are fair. And your code does not contain about ISP and RGB to RAW process.

**Comment by cuiziteng** [comment]
We will renew the LOL-v1 results in the lastest version, and the RGB2RAW process is the network encoder (local branch), please see the [paper](https://openaccess.thecvf.com/content_CVPR_2020/papers/Afifi_Deep_White-Balance_Editing_CVPR_2020_paper.pdf) if you confused.
