### ISSUE TITLE
test on 1080p images

### ISSUE THREAD

**Issue by Yiming0416** [cuiziteng/Illumination-Adaptive-Transformer#61]
Hi,

Thanks for your great work and open-sourcing the code. Have you ever tried running inference on 1080p images? I am using a single RTX TITAN card with 24GB RAM and I got an CUDA out of memory error when running inference on 1080p images. Thanks.

**Comment by cuiziteng** [comment]
Thanks for your interest, IAT's shortage is that it occupies more cache memory, this is because of the depth-wise convolution, so maybe you could resize the image or use higher memory GPUs.
