### ISSUE TITLE
你好，我怎么样才能在最新版的mmdetection中使用dataset_type='ExdarkDataset'?

### ISSUE THREAD

**Issue by Panhonganadd** [cuiziteng/Illumination-Adaptive-Transformer#62]

**Comment by Panhonganadd** [comment]
我最近在学mmdetection，然后想用你们提供的exdark数据集训练模型，但是不知道你们是怎么定义的适合exdark的新的dataset_type

**Comment by cuiziteng** [comment]
数据集格式定义在 https://github.com/cuiziteng/Illumination-Adaptive-Transformer/tree/main/IAT_high/IAT_mmdetection/mmdet/datasets下面的https://github.com/cuiziteng/Illumination-Adaptive-Transformer/blob/main/IAT_high/IAT_mmdetection/mmdet/datasets/exdark.py文件中，采用的VOC格式数据
