### ISSUE TITLE
Single gpu training

### ISSUE THREAD

**Issue by thisisqiaoqiao** [cuiziteng/Illumination-Adaptive-Transformer#64]
[Exposure Correction]，May I ask how to train using a single gpu?

**Comment by cuiziteng** [comment]
Yes, you can follow the low-light enhancement training file to change your code.

**Comment by cuiziteng** [comment]
import torch
import torch.nn as nn
import torch.optim
import torch.nn.functional as F

import os
import argparse
import numpy as np
import random
from torchvision.models import vgg16
from torch.utils.data import DataLoader

from dataloader.data_loader_exposure import exposure_loader
from net.model import Dynamic_CS_1D

from IQA_pytorch import SSIM
from utils import PSNR, validation, LossNetwork

parser = argparse.ArgumentParser()
# Train Path
parser.add_argument('--gpu_id', type=str, default=1)
parser.add_argument('--img_path', type=str, default="/data/unagi0/cui_data/light_dataset/Exposure_CVPR21/train/INPUT_IMAGES")
parser.add_argument('--img_val_path', type=str, default="/data/unagi0/cui_data/light_dataset/Exposure_CVPR21/validation/INPUT_IMAGES")
parser.add_argument("--normalize", action="store_true", help="Default not Normalize in exposure training.")
# Optimize Parameter
parser.add_argument('--batch_size', type=int, default=4)
parser.add_argument('--lr', type=float, default=1e-5)   # for batch size 4x2=8
parser.add_argument('--weight_decay', type=float, default=0.0002)
parser.add_argument('--pretrain_dir', type=str, default=None)
# Network Parameters
# parser.add_argument('--dim_number', type=int, default=48)
# parser.add_argument('--block_number', type=int, default=3)
parser.add_argument('--t_range', type=int, default=500)
# Epoch Number
parser.add_argument('--num_epochs', type=int, default=50)
parser.add_argument('--display_iter', type=int, default=50)
parser.add_argument('--snapshots_folder', type=str, default="workdirs/snapshots_folder_exposure_1d")

config = parser.parse_args()

print(config)
os.environ['CUDA_VISIBLE_DEVICES'] = str(config.gpu_id)
if not os.path.exists(config.snapshots_folder):
    os.makedirs(config.snapshots_folder)


# Model Setting
model = Dynamic_CS_1D(config.t_range).cuda()
if config.pretrain_dir is not None:
    model.load_state_dict(torch.load(config.pretrain_dir))

print('normalize', config.normalize)
# Data Setting
train_dataset = exposure_loader(images_path=config.img_path, normalize=config.normalize)
train_loader = DataLoader(train_dataset, batch_size=config.batch_size, shuffle=True, num_workers=8,
                                           pin_memory=True)
        
val_dataset = exposure_loader(images_path=config.img_val_path, mode='val', normalize=config.normalize)
val_loader = DataLoader(val_dataset, batch_size=1, shuffle=False, num_workers=8, pin_memory=True)

# Loss & Optimizer Setting & Metric
vgg_model = vgg16(pretrained=True).features[:16]
vgg_model = vgg_model.cuda()

for param in vgg_model.parameters():
    param.requires_grad = False

# dynamic_head_params = list(map(id, model.atten.parameters()))
# base_params = filter(lambda p: id(p) not in dynamic_head_params, model.parameters())

# params = [{"params": model.atten.parameters(), "lr": config.lr*10},
#         {"params": base_params, "lr": config.lr}]

# optimizer = torch.optim.Adam(params, weight_decay=config.weight_decay)

optimizer = torch.optim.Adam(model.parameters(), lr=config.lr, weight_decay=config.weight_decay)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=config.num_epochs)

device = next(model.parameters()).device


L1_loss = nn.L1Loss()
L1_smooth_loss = F.smooth_l1_loss

loss_network = LossNetwork(vgg_model)
loss_network.eval()

ssim = SSIM()
psnr = PSNR()
ssim_high = 0
psnr_high = 0


model.train()
print('######## Start Dynamic_CS Training #########')
for epoch in range(config.num_epochs):
    # adjust_learning_rate(optimizer, epoch)
    print('the epoch is:', epoch)
    
    for iteration, imgs in enumerate(train_loader):
        low_img, high_img = imgs[0].cuda(), imgs[1].cuda()
        # Checking!
        #visualization(low_img, 'show/low', iteration)
        #visualization(high_img, 'show/high', iteration)
        optimizer.zero_grad()
        model.train()
        enhance_img = model(low_img)
        
        #loss = L1_loss(enhance_img, high_img)
        loss = L1_smooth_loss(enhance_img, high_img)+0.04*loss_network(enhance_img, high_img)
        #print(loss)
        loss.backward()
        # for name, parms in model.named_parameters():
        #     print('-->name', name, '-->grad_requir', parms.requires_grad, \
        #         '-->grad_value',parms.grad.mean())
        optimizer.step()
        scheduler.step()

        if ((iteration + 1) % config.display_iter) == 0:
            print("Loss at iteration", iteration + 1, ":", loss.item())
    
    
    model.eval()

    PSNR_mean, SSIM_mean = validation(model, val_loader)

    with open(config.snapshots_folder + '/log.txt', 'a+') as f:
        f.write('epoch' + str(epoch) + ':' + 'the SSIM is' + str(SSIM_mean) + 'the PSNR is' + str(PSNR_mean) + '\n')

    if SSIM_mean > ssim_high:
        ssim_high = SSIM_mean
        print('the highest SSIM value is:', str(ssim_high))
        torch.save(model.state_dict(), os.path.join(config.snapshots_folder, "best_Epoch" + '.pth'))

    f.close()

**Comment by cuiziteng** [comment]
`import torch
import torch.nn as nn
import torch.optim
import torch.nn.functional as F

import os
import argparse
import numpy as np
import random
from torchvision.models import vgg16
from torch.utils.data import DataLoader

from dataloader.data_loader_exposure import exposure_loader
from net.model import Dynamic_CS_1D

from IQA_pytorch import SSIM
from utils import PSNR, validation, LossNetwork

parser = argparse.ArgumentParser()
# Train Path
parser.add_argument('--gpu_id', type=str, default=1)
parser.add_argument('--img_path', type=str, default="/data/unagi0/cui_data/light_dataset/Exposure_CVPR21/train/INPUT_IMAGES")
parser.add_argument('--img_val_path', type=str, default="/data/unagi0/cui_data/light_dataset/Exposure_CVPR21/validation/INPUT_IMAGES")
parser.add_argument("--normalize", action="store_true", help="Default not Normalize in exposure training.")
# Optimize Parameter
parser.add_argument('--batch_size', type=int, default=4)
parser.add_argument('--lr', type=float, default=1e-5)   # for batch size 4x2=8
parser.add_argument('--weight_decay', type=float, default=0.0002)
parser.add_argument('--pretrain_dir', type=str, default=None)
# Network Parameters
# parser.add_argument('--dim_number', type=int, default=48)
# parser.add_argument('--block_number', type=int, default=3)
parser.add_argument('--t_range', type=int, default=500)
# Epoch Number
parser.add_argument('--num_epochs', type=int, default=50)
parser.add_argument('--display_iter', type=int, default=50)
parser.add_argument('--snapshots_folder', type=str, default="workdirs/snapshots_folder_exposure_1d")

config = parser.parse_args()

print(config)
os.environ['CUDA_VISIBLE_DEVICES'] = str(config.gpu_id)
if not os.path.exists(config.snapshots_folder):
    os.makedirs(config.snapshots_folder)


# Model Setting
model = Dynamic_CS_1D(config.t_range).cuda()
if config.pretrain_dir is not None:
    model.load_state_dict(torch.load(config.pretrain_dir))

print('normalize', config.normalize)
# Data Setting
train_dataset = exposure_loader(images_path=config.img_path, normalize=config.normalize)
train_loader = DataLoader(train_dataset, batch_size=config.batch_size, shuffle=True, num_workers=8,
                                           pin_memory=True)
        
val_dataset = exposure_loader(images_path=config.img_val_path, mode='val', normalize=config.normalize)
val_loader = DataLoader(val_dataset, batch_size=1, shuffle=False, num_workers=8, pin_memory=True)

# Loss & Optimizer Setting & Metric
vgg_model = vgg16(pretrained=True).features[:16]
vgg_model = vgg_model.cuda()

for param in vgg_model.parameters():
    param.requires_grad = False

# dynamic_head_params = list(map(id, model.atten.parameters()))
# base_params = filter(lambda p: id(p) not in dynamic_head_params, model.parameters())

# params = [{"params": model.atten.parameters(), "lr": config.lr*10},
#         {"params": base_params, "lr": config.lr}]

# optimizer = torch.optim.Adam(params, weight_decay=config.weight_decay)

optimizer = torch.optim.Adam(model.parameters(), lr=config.lr, weight_decay=config.weight_decay)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=config.num_epochs)

device = next(model.parameters()).device


L1_loss = nn.L1Loss()
L1_smooth_loss = F.smooth_l1_loss

loss_network = LossNetwork(vgg_model)
loss_network.eval()

ssim = SSIM()
psnr = PSNR()
ssim_high = 0
psnr_high = 0


model.train()
print('######## Start Dynamic_CS Training #########')
for epoch in range(config.num_epochs):
    # adjust_learning_rate(optimizer, epoch)
    print('the epoch is:', epoch)
    
    for iteration, imgs in enumerate(train_loader):
        low_img, high_img = imgs[0].cuda(), imgs[1].cuda()
        # Checking!
        #visualization(low_img, 'show/low', iteration)
        #visualization(high_img, 'show/high', iteration)
        optimizer.zero_grad()
        model.train()
        enhance_img = model(low_img)
        
        #loss = L1_loss(enhance_img, high_img)
        loss = L1_smooth_loss(enhance_img, high_img)+0.04*loss_network(enhance_img, high_img)
        #print(loss)
        loss.backward()
        # for name, parms in model.named_parameters():
        #     print('-->name', name, '-->grad_requir', parms.requires_grad, \
        #         '-->grad_value',parms.grad.mean())
        optimizer.step()
        scheduler.step()

        if ((iteration + 1) % config.display_iter) == 0:
            print("Loss at iteration", iteration + 1, ":", loss.item())
    
    
    model.eval()

    PSNR_mean, SSIM_mean = validation(model, val_loader)

    with open(config.snapshots_folder + '/log.txt', 'a+') as f:
        f.write('epoch' + str(epoch) + ':' + 'the SSIM is' + str(SSIM_mean) + 'the PSNR is' + str(PSNR_mean) + '\n')

    if SSIM_mean > ssim_high:
        ssim_high = SSIM_mean
        print('the highest SSIM value is:', str(ssim_high))
        torch.save(model.state_dict(), os.path.join(config.snapshots_folder, "best_Epoch" + '.pth'))

    f.close()

    `

**Comment by cuiziteng** [comment]
`import torch
import torch.nn as nn
import torch.optim
import torch.nn.functional as F

import os
import argparse
import numpy as np
import random
from torchvision.models import vgg16
from torch.utils.data import DataLoader

from dataloader.data_loader_exposure import exposure_loader
from net.model import Dynamic_CS_1D

from IQA_pytorch import SSIM
from utils import PSNR, validation, LossNetwork

parser = argparse.ArgumentParser()

parser.add_argument('--gpu_id', type=str, default=1)
parser.add_argument('--img_path', type=str, default="/data/unagi0/cui_data/light_dataset/Exposure_CVPR21/train/INPUT_IMAGES")
parser.add_argument('--img_val_path', type=str, default="/data/unagi0/cui_data/light_dataset/Exposure_CVPR21/validation/INPUT_IMAGES")
parser.add_argument("--normalize", action="store_true", help="Default not Normalize in exposure training.")

parser.add_argument('--batch_size', type=int, default=4)
parser.add_argument('--lr', type=float, default=1e-5)   # for batch size 4x2=8
parser.add_argument('--weight_decay', type=float, default=0.0002)
parser.add_argument('--pretrain_dir', type=str, default=None)

# parser.add_argument('--dim_number', type=int, default=48)
# parser.add_argument('--block_number', type=int, default=3)
parser.add_argument('--t_range', type=int, default=500)

parser.add_argument('--num_epochs', type=int, default=50)
parser.add_argument('--display_iter', type=int, default=50)
parser.add_argument('--snapshots_folder', type=str, default="workdirs/snapshots_folder_exposure_1d")

config = parser.parse_args()

print(config)
os.environ['CUDA_VISIBLE_DEVICES'] = str(config.gpu_id)
if not os.path.exists(config.snapshots_folder):
    os.makedirs(config.snapshots_folder)



model = Dynamic_CS_1D(config.t_range).cuda()
if config.pretrain_dir is not None:
    model.load_state_dict(torch.load(config.pretrain_dir))

print('normalize', config.normalize)

train_dataset = exposure_loader(images_path=config.img_path, normalize=config.normalize)
train_loader = DataLoader(train_dataset, batch_size=config.batch_size, shuffle=True, num_workers=8,
                                           pin_memory=True)
        
val_dataset = exposure_loader(images_path=config.img_val_path, mode='val', normalize=config.normalize)
val_loader = DataLoader(val_dataset, batch_size=1, shuffle=False, num_workers=8, pin_memory=True)


vgg_model = vgg16(pretrained=True).features[:16]
vgg_model = vgg_model.cuda()

for param in vgg_model.parameters():
    param.requires_grad = False



# optimizer = torch.optim.Adam(params, weight_decay=config.weight_decay)

optimizer = torch.optim.Adam(model.parameters(), lr=config.lr, weight_decay=config.weight_decay)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=config.num_epochs)

device = next(model.parameters()).device


L1_loss = nn.L1Loss()
L1_smooth_loss = F.smooth_l1_loss

loss_network = LossNetwork(vgg_model)
loss_network.eval()

ssim = SSIM()
psnr = PSNR()
ssim_high = 0
psnr_high = 0


model.train()
print('######## Start Dynamic_CS Training #########')
for epoch in range(config.num_epochs):
    
    print('the epoch is:', epoch)
    
    for iteration, imgs in enumerate(train_loader):
        low_img, high_img = imgs[0].cuda(), imgs[1].cuda()
        
        optimizer.zero_grad()
        model.train()
        enhance_img = model(low_img)
        
        
        loss = L1_smooth_loss(enhance_img, high_img)+0.04*loss_network(enhance_img, high_img)
      
        loss.backward()
        
        optimizer.step()
        scheduler.step()

        if ((iteration + 1) % config.display_iter) == 0:
            print("Loss at iteration", iteration + 1, ":", loss.item())
    
    
    model.eval()

    PSNR_mean, SSIM_mean = validation(model, val_loader)

    with open(config.snapshots_folder + '/log.txt', 'a+') as f:
        f.write('epoch' + str(epoch) + ':' + 'the SSIM is' + str(SSIM_mean) + 'the PSNR is' + str(PSNR_mean) + '\n')

    if SSIM_mean > ssim_high:
        ssim_high = SSIM_mean
        print('the highest SSIM value is:', str(ssim_high))
        torch.save(model.state_dict(), os.path.join(config.snapshots_folder, "best_Epoch" + '.pth'))

    f.close()

    `

**Comment by cuiziteng** [comment]
`import torch
import torch.nn as nn
import torch.optim
import torch.nn.functional as F

import os
import argparse
import numpy as np
import random
from torchvision.models import vgg16
from torch.utils.data import DataLoader

from dataloader.data_loader_exposure import exposure_loader
from net.model import Dynamic_CS_1D

from IQA_pytorch import SSIM
from utils import PSNR, validation, LossNetwork

parser = argparse.ArgumentParser()

parser.add_argument('--gpu_id', type=str, default=1)
parser.add_argument('--img_path', type=str, default="/data/unagi0/cui_data/light_dataset/Exposure_CVPR21/train/INPUT_IMAGES")
parser.add_argument('--img_val_path', type=str, default="/data/unagi0/cui_data/light_dataset/Exposure_CVPR21/validation/INPUT_IMAGES")
parser.add_argument("--normalize", action="store_true", help="Default not Normalize in exposure training.")

parser.add_argument('--batch_size', type=int, default=4)
parser.add_argument('--lr', type=float, default=1e-5)   # for batch size 4x2=8
parser.add_argument('--weight_decay', type=float, default=0.0002)
parser.add_argument('--pretrain_dir', type=str, default=None)

parser.add_argument('--t_range', type=int, default=500)

parser.add_argument('--num_epochs', type=int, default=50)
parser.add_argument('--display_iter', type=int, default=50)
parser.add_argument('--snapshots_folder', type=str, default="workdirs/snapshots_folder_exposure_1d")

config = parser.parse_args()

print(config)
os.environ['CUDA_VISIBLE_DEVICES'] = str(config.gpu_id)
if not os.path.exists(config.snapshots_folder):
    os.makedirs(config.snapshots_folder)


model = Dynamic_CS_1D(config.t_range).cuda()
if config.pretrain_dir is not None:
    model.load_state_dict(torch.load(config.pretrain_dir))

train_dataset = exposure_loader(images_path=config.img_path, normalize=config.normalize)
train_loader = DataLoader(train_dataset, batch_size=config.batch_size, shuffle=True, num_workers=8,
                                           pin_memory=True)
        
val_dataset = exposure_loader(images_path=config.img_val_path, mode='val', normalize=config.normalize)
val_loader = DataLoader(val_dataset, batch_size=1, shuffle=False, num_workers=8, pin_memory=True)

vgg_model = vgg16(pretrained=True).features[:16]
vgg_model = vgg_model.cuda()

for param in vgg_model.parameters():
    param.requires_grad = False

optimizer = torch.optim.Adam(model.parameters(), lr=config.lr, weight_decay=config.weight_decay)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=config.num_epochs)

device = next(model.parameters()).device


L1_loss = nn.L1Loss()
L1_smooth_loss = F.smooth_l1_loss

loss_network = LossNetwork(vgg_model)
loss_network.eval()

ssim = SSIM()
psnr = PSNR()
ssim_high = 0
psnr_high = 0


model.train()
print('######## Start Dynamic_CS Training #########')
for epoch in range(config.num_epochs):
    # adjust_learning_rate(optimizer, epoch)
    print('the epoch is:', epoch)
    
    for iteration, imgs in enumerate(train_loader):
        low_img, high_img = imgs[0].cuda(), imgs[1].cuda()
        
        optimizer.zero_grad()
        model.train()
        enhance_img = model(low_img)
        
        
        loss = L1_smooth_loss(enhance_img, high_img)+0.04*loss_network(enhance_img, high_img)
        
        loss.backward()
        
        optimizer.step()
        scheduler.step()

        if ((iteration + 1) % config.display_iter) == 0:
            print("Loss at iteration", iteration + 1, ":", loss.item())
    
    
    model.eval()

    PSNR_mean, SSIM_mean = validation(model, val_loader)

    with open(config.snapshots_folder + '/log.txt', 'a+') as f:
        f.write('epoch' + str(epoch) + ':' + 'the SSIM is' + str(SSIM_mean) + 'the PSNR is' + str(PSNR_mean) + '\n')

    if SSIM_mean > ssim_high:
        ssim_high = SSIM_mean
        print('the highest SSIM value is:', str(ssim_high))
        torch.save(model.state_dict(), os.path.join(config.snapshots_folder, "best_Epoch" + '.pth'))

    f.close()

    `

**Comment by cuiziteng** [comment]
``import torch
import torch.nn as nn
import torch.optim
import torch.nn.functional as F

import os
import argparse
import numpy as np
import random
from torchvision.models import vgg16
from torch.utils.data import DataLoader

from dataloader.data_loader_exposure import exposure_loader
from net.model import Dynamic_CS_1D

from IQA_pytorch import SSIM
from utils import PSNR, validation, LossNetwork

parser = argparse.ArgumentParser()

parser.add_argument('--gpu_id', type=str, default=1)
parser.add_argument('--img_path', type=str, default="/data/unagi0/cui_data/light_dataset/Exposure_CVPR21/train/INPUT_IMAGES")
parser.add_argument('--img_val_path', type=str, default="/data/unagi0/cui_data/light_dataset/Exposure_CVPR21/validation/INPUT_IMAGES")
parser.add_argument("--normalize", action="store_true", help="Default not Normalize in exposure training.")

parser.add_argument('--batch_size', type=int, default=4)
parser.add_argument('--lr', type=float, default=1e-5)   # for batch size 4x2=8
parser.add_argument('--weight_decay', type=float, default=0.0002)
parser.add_argument('--pretrain_dir', type=str, default=None)

parser.add_argument('--t_range', type=int, default=500)

parser.add_argument('--num_epochs', type=int, default=50)
parser.add_argument('--display_iter', type=int, default=50)
parser.add_argument('--snapshots_folder', type=str, default="workdirs/snapshots_folder_exposure_1d")

config = parser.parse_args()

print(config)
os.environ['CUDA_VISIBLE_DEVICES'] = str(config.gpu_id)
if not os.path.exists(config.snapshots_folder):
    os.makedirs(config.snapshots_folder)


model = Dynamic_CS_1D(config.t_range).cuda()
if config.pretrain_dir is not None:
    model.load_state_dict(torch.load(config.pretrain_dir))

train_dataset = exposure_loader(images_path=config.img_path, normalize=config.normalize)
train_loader = DataLoader(train_dataset, batch_size=config.batch_size, shuffle=True, num_workers=8,
                                           pin_memory=True)
        
val_dataset = exposure_loader(images_path=config.img_val_path, mode='val', normalize=config.normalize)
val_loader = DataLoader(val_dataset, batch_size=1, shuffle=False, num_workers=8, pin_memory=True)

vgg_model = vgg16(pretrained=True).features[:16]
vgg_model = vgg_model.cuda()

for param in vgg_model.parameters():
    param.requires_grad = False

optimizer = torch.optim.Adam(model.parameters(), lr=config.lr, weight_decay=config.weight_decay)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=config.num_epochs)

device = next(model.parameters()).device


L1_loss = nn.L1Loss()
L1_smooth_loss = F.smooth_l1_loss

loss_network = LossNetwork(vgg_model)
loss_network.eval()

ssim = SSIM()
psnr = PSNR()
ssim_high = 0
psnr_high = 0


model.train()
print('######## Start Dynamic_CS Training #########')
for epoch in range(config.num_epochs):
    
    print('the epoch is:', epoch)
    
    for iteration, imgs in enumerate(train_loader):
        low_img, high_img = imgs[0].cuda(), imgs[1].cuda()
        
        optimizer.zero_grad()
        model.train()
        enhance_img = model(low_img)
        
        
        loss = L1_smooth_loss(enhance_img, high_img)+0.04*loss_network(enhance_img, high_img)
        
        loss.backward()
        
        optimizer.step()
        scheduler.step()

        if ((iteration + 1) % config.display_iter) == 0:
            print("Loss at iteration", iteration + 1, ":", loss.item())
    
    
    model.eval()

    PSNR_mean, SSIM_mean = validation(model, val_loader)

    with open(config.snapshots_folder + '/log.txt', 'a+') as f:
        f.write('epoch' + str(epoch) + ':' + 'the SSIM is' + str(SSIM_mean) + 'the PSNR is' + str(PSNR_mean) + '\n')

    if SSIM_mean > ssim_high:
        ssim_high = SSIM_mean
        print('the highest SSIM value is:', str(ssim_high))
        torch.save(model.state_dict(), os.path.join(config.snapshots_folder, "best_Epoch" + '.pth'))

    f.close()

    ``

**Comment by thisisqiaoqiao** [comment]
Thank you for your reply. I have an additional question. What configuration did you use for training? I followed   #35 's solution and found that the speed was slow during training. Can I increase the batch size? This will have an impact on performance.

**Comment by cuiziteng** [comment]
Sure, you can increase the batchsize if your GPU memory enough, and meanwhile do not forget to adjust the learning rate as follow:

<img width="573" alt="image" src="https://github.com/cuiziteng/Illumination-Adaptive-Transformer/assets/55396225/efd8d8ff-945d-4316-9d75-7d9ee89e9213">

**Comment by thisisqiaoqiao** [comment]
Thanks for your reply, I will experiment.
