### ISSUE TITLE
关于目标检测

### ISSUE THREAD

**Issue by aowuaaa** [cuiziteng/Illumination-Adaptive-Transformer#65]
您好！看完了论文，对这篇工作很感兴趣。因为我是刚开始学习低光增强的，所以对有些东西不太了解。表4 目标检测的map，是在别的增强数据集上训练，然后在exdark数据集上增强，再进行检测吗？

**Comment by cuiziteng** [comment]
表4的结果是这样的，但是可以看看supp里的Fig5和表6，联合一起训练的效果会更好。

**Comment by aowuaaa** [comment]
好的，明白了，谢谢，还有一个问题，增强部分是在哪个数据集上训练的呢

**Comment by aowuaaa** [comment]
谢谢谢谢，谢谢解答
