### ISSUE TITLE
论文原理疑问

### ISSUE THREAD

**Issue by jhxiang** [cuiziteng/Illumination-Adaptive-Transformer#66]
感谢作者出色的工作！我有个疑问，按论文里的说法，local_net将sRGB变为raw-RGB图像，global_branch再将raw-RGB图像增益为正常亮度sRGB图像。那为什么代码中不加全局分支时只要local_net就能得到正常亮度sRGB图像呢？希望作者解答下
![1700659017174](https://github.com/cuiziteng/Illumination-Adaptive-Transformer/assets/103103527/b04b5881-43ca-4c9c-b72c-c67f8207098e)

**Comment by jhxiang** [comment]
追加一个疑问，global分支的思路很好理解，我不是很理解local分支的思路，为什么local网络这么设计以及这个local网络实现了什么功能？

**Comment by jhxiang** [comment]
@cuiziteng 您好，希望作者大大能解答一下疑问，感激不尽

**Comment by cuiziteng** [comment]
您好，local这里网络单独使用是不合理的，只是加了一个ablation study，local网络设计上的原理是想用一个最小二乘法来做拟合，b = a*x+y，x 和 y分别是乘法分支和加法分支的输出，目的是希望一个最小二乘可以拟合我们想要的情况。

**Comment by jhxiang** [comment]
感谢您的回复，我明白了，不过local_net单独使用psnr都比一些方法高了，感觉单独使用是不是可行？

**Comment by cuiziteng** [comment]
我觉得也是可行的，如果这样的话就相当于只用一个最小二乘法做拟合，参数量也非常少。

**Comment by jhxiang** [comment]
感谢回复!谢谢解答
