### ISSUE TITLE
能否提供在exdark上的训练日志？

### ISSUE THREAD

**Issue by Nanakl** [cuiziteng/Illumination-Adaptive-Transformer#68]
我在自己的数据集（暗光目标检测）上训练时，每个epoch在测试集上测试map，map随epoch波动明显，可能是什么原因造成的？

![微信截图_20231219093731](https://github.com/cuiziteng/Illumination-Adaptive-Transformer/assets/81354300/130706c8-9571-4bd3-8bab-ff2b5b50171d)

**Comment by cuiziteng** [comment]
可能是模型学习率，还有是否加载COCO预训练模型。
