### ISSUE TITLE
Unfair comparison

### ISSUE THREAD

**Issue by echosum** [cuiziteng/Illumination-Adaptive-Transformer#7]
Your IAT is trained on 689 LOL training images.
But the original LOL dataset just contains 485 training images.
Table 1 shows the results of the LOL dataset. Other methods, like MAXIM, are trained on the original dataset.
More training data means better results. It seems the author extends external training data for better results. 
The author should give a reasonable explanation for why conducts so unfair comparison.

**Comment by cuiziteng** [comment]
Thanks for your question, we have renew our Arxiv version, and the renewed results on LOL-V1 results is 23.38 and 0.809
<img width="730" alt="image" src="https://user-images.githubusercontent.com/55396225/182034677-a864a8b1-68f1-4b56-a9dd-757f772ed5c5.png">

**Comment by echosum** [comment]
Good job. Thanks for your reply!
