### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Qqsoe** [cuiziteng/Illumination-Adaptive-Transformer#74]
作者您好，image enhance，在改动了模型结构后，低光增强的训练和测试没有问题，但曝光矫正训练完后，加载训练权重测试时出现 Missing key(s) in state_dict的错误，请问这该如何解决？

**Comment by cuiziteng** [comment]
检查一下是不是没有load对你训练的权重？

**Comment by Qqsoe** [comment]
global分支中最后两个1x1卷积在代码里怎么找不到
