### ISSUE TITLE
您好，您是否尝试过曝光矫正和暗光增强一起做，靠网络调整图像亮度

### ISSUE THREAD

**Issue by ZziTaiLeo** [cuiziteng/Illumination-Adaptive-Transformer#75]
看代码里过曝光和暗光增强分开训，同一个网络针对不同场景的datasets训。您是否试过将 暗光增强喝曝光矫正的数据集均匀合在一起训练？其中有发生了什么问题呢

**Comment by cuiziteng** [comment]
这篇论文没有尝试，我觉得很有意思，您可以试一下

**Comment by ZziTaiLeo** [comment]
> 这篇论文没有尝试，我觉得很有意思，您可以试一下

好的，谢谢您的回复
