### ISSUE TITLE
多GPU训练

### ISSUE THREAD

**Issue by znmzdx-zrh** [cuiziteng/Illumination-Adaptive-Transformer#78]
您好，请问一下可以使用多GPU训练吗？实验室的卡只有11G，我在训练LOL-V2时爆显存了，目前想把模型分到两张卡上。但我发现就算只指定两张卡，如5、6卡之后，它总是在0卡上还占一些显存。

**Comment by cuiziteng** [comment]
可以的，您参考一下exposure correction那里的[训练代码设置](https://github.com/cuiziteng/Illumination-Adaptive-Transformer/blob/main/IAT_enhance/train_exposure.py)，把LOL-V2的训练代码转成多GPU训练就好，然后训练时候再指定CUDA_VISIBLE_DEVICES=5,6

**Comment by znmzdx-zrh** [comment]
> 可以的，您参考一下exposure correction那里的[训练代码设置](https://github.com/cuiziteng/Illumination-Adaptive-Transformer/blob/main/IAT_enhance/train_exposure.py)，把LOL-V2的训练代码转成多GPU训练就好，然后训练时候再指定CUDA_VISIBLE_DEVICES=5,6

嗯嗯好滴感谢您的回复，我昨天改了一下代码可以实现多卡训练了
