### ISSUE TITLE
cannot find back-propagation step in detection code

### ISSUE THREAD

**Issue by masterpeas** [cuiziteng/Illumination-Adaptive-Transformer#8]
I ran the tools/train.py but cannot find which line denotes back-propagation. Could you tell me where it is?

**Comment by cuiziteng** [comment]
Hello, since this project is based on mmdetection, the back-propagation is in MMCV toolbox, please refer to [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/epoch_based_runner.py).

From tools/train.py -- mmdet/apis/train.py -- mmcv

**Comment by masterpeas** [comment]
> Hello, since this project is based on mmdetection, the back-propagation is in MMCV toolbox, please refer to [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/epoch_based_runner.py).
> 
> From tools/train.py -- mmdet/apis/train.py -- mmcv
> 
> For more details you could refer to [mmdetection](https://mmdetection.readthedocs.io/en/v2.21.0/get_started.html) toolbox.

I'll learn how to use the mmdetection toolbox. Thx! (*^_^*)
