### ISSUE TITLE
Evaluation pretrain model on LOL-V1 dataset

### ISSUE THREAD

**Issue by minhthien2206** [cuiziteng/Illumination-Adaptive-Transformer#9]
Hi authors, 
I try to run the code to evaluate the model on the LOL-V1 dataset. I follow as your command: "python evaluation_lol_v1.py --img_val_path Your_Path/eval15/low/". However, I can not get the results. The terminal show as:
![image](https://user-images.githubusercontent.com/34763839/184119038-42503ce3-8ed5-4390-8a4b-6a1bce67ae72.png)
Could you please show me how to fix and obtain the results?

**Comment by cuiziteng** [comment]
Thx, I'll fix it soon~

**Comment by cuiziteng** [comment]
Hello! It seem like you haven't correct load the images in LOL-V1 dataset , you need to first download LOL-V1 dataset from the this website: https://daooshee.github.io/BMVC2018website/, and then map the dataset as the format:

Your_Path (where you place LOL-V1 dataset)
  -- our485
      -- high
      -- low
  -- eval15
      -- high
      -- low

Note that Your_Path is not a certain path, it is the path you save LOL-V1 dataset, any question else please drop here~

**Comment by minhthien2206** [comment]
Hi authors,
I already formatted it like your guidance.
![image](https://user-images.githubusercontent.com/34763839/184135321-da93ebcf-8598-47bb-a4dc-8dc9592200bb.png)
And inside the code, I also change the link as follows:
![image](https://user-images.githubusercontent.com/34763839/184135460-e07e5195-b60b-448b-9905-0c2b1937b7d5.png)
The error still happens:
![image](https://user-images.githubusercontent.com/34763839/184135591-997eaa35-13ed-4cab-bbc5-4d60157572d0.png)

**Comment by cuiziteng** [comment]
Hello, don't forget to add a '/' in the end of the path, change it to './datasets/LOL_v1/eval15/low/' and try again~

**Comment by minhthien2206** [comment]
Yes, thanks for your answer. I already fixed the error.
